# Generated by Django 5.0.7 on 2024-07-30 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uid",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="登录账号"
                    ),
                ),
                ("password", models.CharField(max_length=100, verbose_name="登录密码")),
                ("nickname", models.CharField(max_length=50, verbose_name="昵称")),
                (
                    "group",
                    models.SmallIntegerField(
                        default=2,
                        help_text="1=超级管理员；2=管理员；3=普通用户",
                        verbose_name="分组",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        default=1, help_text="0=冻结；1=正常；", verbose_name="状态"
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "last_login_datetime",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="登录验证Token",
                    ),
                ),
                (
                    "access_token_expire",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="登录Token过期时间",
                    ),
                ),
            ],
        ),
    ]
