# Generated by Django 5.0.7 on 2024-07-29 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('author_uid', models.IntegerField(verbose_name='作者uid')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
        ),
    ]
